apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    path: deployment/test-app-dev
    repoURL: ghcr.io/philipsabri
    targetRevision: "^0.x.x"
    chart: test-app-chart
    helm:
      releaseName: test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
