apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    chart: test-app-chart
    repoURL: https://github.com/philipsabri/test-app.git
    targetRevision: "0.1.8"
    helm:
      releaseName: test-app
      valueFiles:
        - test-app-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
