apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://artifactory.karolinska.se/artifactory/backstage-helm-snapshot
    targetRevision: "0.*.*-beta.*"
    chart: backstage-app-chart
    helm:
      releaseName: test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
