apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    path: deployment/test-app-dev
    repoURL: https://github.com/philipsabri/argocd.git
    targetRevision: main
    helm:
      releaseName: test-app
      valueFiles:
        - test-app-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
